// <auto-generated />
using System;
using FinnAir.DataLayer.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FinnAir.DataLayer.Migrations
{
    [DbContext(typeof(FinnAirContext))]
    [Migration("20191229174727_reseedData")]
    partial class reseedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FinnAir.DataLayer.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = "FIN123"
                        },
                        new
                        {
                            Id = "FIN124"
                        },
                        new
                        {
                            Id = "FIN125"
                        },
                        new
                        {
                            Id = "FIN126"
                        },
                        new
                        {
                            Id = "FIN127"
                        },
                        new
                        {
                            Id = "FIN128"
                        });
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.BookingFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingId");

                    b.Property<int>("FlightId");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("FlightId");

                    b.ToTable("BookingFlights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = "FIN123",
                            FlightId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = "FIN124",
                            FlightId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookingId = "FIN124",
                            FlightId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookingId = "FIN125",
                            FlightId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookingId = "FIN125",
                            FlightId = 4
                        });
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ArrivalAirportCode")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalAirport = "Brussel",
                            ArrivalAirportCode = "BRU",
                            ArrivalDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarrierCode = "W12",
                            DepartureAirport = "Stuttgart",
                            DepartureAirportCode = "STU",
                            DepartureDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "FA2490"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalAirport = "Brussel",
                            ArrivalAirportCode = "BRU",
                            ArrivalDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarrierCode = "A11",
                            DepartureAirport = "Stuttgart",
                            DepartureAirportCode = "STU",
                            DepartureDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "FA2490"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalAirport = "Brussel",
                            ArrivalAirportCode = "BRU",
                            ArrivalDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarrierCode = "B13",
                            DepartureAirport = "Stuttgart",
                            DepartureAirportCode = "STU",
                            DepartureDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "FA2490"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalAirport = "Brussel",
                            ArrivalAirportCode = "BRU",
                            ArrivalDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarrierCode = "C15",
                            DepartureAirport = "Stuttgart",
                            DepartureAirportCode = "STU",
                            DepartureDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "FA2490"
                        });
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(225);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(225);

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = "FIN123",
                            Email = "gbengaoluyide@gmail.com",
                            Firstname = "Gbenga",
                            LastName = "Oluyide"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = "FIN124",
                            Email = "sadeoluyide@gmail.com",
                            Firstname = "Sade",
                            LastName = "Oluyide"
                        },
                        new
                        {
                            Id = 3,
                            BookingId = "FIN125",
                            Email = "gbade@gmail.com",
                            Firstname = "Gbade",
                            LastName = "Oluyide"
                        },
                        new
                        {
                            Id = 4,
                            BookingId = "FIN126",
                            Email = "bayo@gmail.com",
                            Firstname = "Bayo",
                            LastName = "Oluyide"
                        },
                        new
                        {
                            Id = 5,
                            BookingId = "FIN127",
                            Email = "biibire@gmail.com",
                            Firstname = "Biibire",
                            LastName = "Oluyide"
                        },
                        new
                        {
                            Id = 6,
                            BookingId = "FIN128",
                            Email = "omolaraoluyide@gmail.com",
                            Firstname = "Omolara",
                            LastName = "Oluyide"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.BookingFlight", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.Booking", "Booking")
                        .WithMany("BookingFlight")
                        .HasForeignKey("BookingId");

                    b.HasOne("FinnAir.DataLayer.Model.Flight", "Flight")
                        .WithMany("BookingFlight")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Passenger", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.Booking", "Booking")
                        .WithMany("Passenger")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinnAir.DataLayer.Model.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
