// <auto-generated />
using System;
using FinnAir.DataLayer.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FinnAir.DataLayer.Migrations
{
    [DbContext(typeof(FinnAirContext))]
    [Migration("20191228002458_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FinnAir.DataLayer.Model.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = "FIN123"
                        },
                        new
                        {
                            Id = "FIN124"
                        },
                        new
                        {
                            Id = "FIN125"
                        },
                        new
                        {
                            Id = "FIN126"
                        },
                        new
                        {
                            Id = "FIN127"
                        },
                        new
                        {
                            Id = "FIN128"
                        });
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.BookingFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingId");

                    b.Property<int>("FlightId");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("FlightId");

                    b.ToTable("BookingFlights");
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrivalAirport")
                        .IsRequired();

                    b.Property<string>("ArrivalAirportCode")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("CarrierCode")
                        .IsRequired();

                    b.Property<string>("DepartureAirport")
                        .IsRequired();

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("FlightNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.BookingFlight", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.Booking", "Booking")
                        .WithMany("BookingFlight")
                        .HasForeignKey("BookingId");

                    b.HasOne("FinnAir.DataLayer.Model.Flight", "Flight")
                        .WithMany("BookingFlight")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinnAir.DataLayer.Model.Passenger", b =>
                {
                    b.HasOne("FinnAir.DataLayer.Model.Booking", "Booking")
                        .WithMany("Passenger")
                        .HasForeignKey("BookingId");
                });
#pragma warning restore 612, 618
        }
    }
}
